### ISSUE TITLE
Title is `undefined`

### ISSUE THREAD

**Issue by sveneberth** [viur-framework/vi-admin#1]
The title in the latest vi-admin (`4.0.11`) is `undefined`.

![image](https://github.com/viur-framework/vi-admin/assets/10272292/04f94738-0217-498b-9c05-035da1dabf80)

**Comment by sveneberth** [comment]
The response of `/vi/config` contains `configuration.name: "my name"`. But the title is still _undefined_.

**Comment by XeoN-GHMB** [comment]
a side effect in core 3.6: https://github.com/viur-framework/viur-core/issues/976
Admin delivers now a fallback: https://github.com/viur-framework/vi-vue-components/commit/52d02000653e91db8dc6684a0f934c155e172ad3
