### ISSUE TITLE
Options are not applied in a multiple `SelectBone` with Integer value keys

### ISSUE THREAD

**Issue by sveneberth** [viur-framework/vi-admin#11]
I've a SelectBone like
```py
zip_code = SelectBone(
    descr="my bone",
    multiple=True,
    values={
        i: f"{i}****" for i in range(0, 10)
    }
)
```
The popup contains the keys, but after i select one, it doesn't appear in the input field above
![image](https://github.com/viur-framework/vi-admin/assets/10272292/be214637-c1dc-4921-a104-b78ae3a0e2b9)

**Comment by XeoN-GHMB** [comment]
Seams to be fixed in v.4.0.20
<img width="661" alt="image" src="https://github.com/viur-framework/vi-admin/assets/32266000/e61d2b45-2a12-4c91-a53f-b340d69f5439">

**Comment by XeoN-GHMB** [comment]
ok will be fixed in the next version: https://github.com/viur-framework/vi-vue-utils/commit/509dc523f2e9bf4d90a0b1dd2b13e5eee1acddf0
