### ISSUE TITLE
Indent missing on third layer in the sidebar

### ISSUE THREAD

**Issue by sveneberth** [viur-framework/vi-admin#15]
There is some `marging-left`/`padding-left` missing for the view of a module in a module-group:

![image](https://github.com/viur-framework/vi-admin/assets/10272292/bc03be0b-3813-418f-abd8-1729feebe4ff)

_Module View 1_ and _Module View 2_ should be below _Module_

**Comment by XeoN-GHMB** [comment]
Will be fixed with the next release:
https://github.com/viur-framework/vi-vue-components/commit/21f8248501d8e79861499d11f2cc0e5c20e1ce88
