### ISSUE TITLE
Please add a _reload_ button to `skeleton/add` action

### ISSUE THREAD

**Issue by sveneberth** [viur-framework/vi-admin#18]
I'm currently writing an custom `addSkel`, for this it would be nice to reload the _add pane_ to get the new structure from the server

![image](https://github.com/viur-framework/vi-admin/assets/10272292/3a2ec5eb-6850-454d-aff9-3bb861fcbd9b)

**Comment by XeoN-GHMB** [comment]
Will be available in the next release:
https://github.com/viur-framework/vi-vue-components/commit/a42616cc220e84f7d8a12c51da1de6fa5f2385e5
