### ISSUE TITLE
Please add the _save and close_ button to skeleton/add and edit action #18

### ISSUE THREAD

**Issue by sveneberth** [viur-framework/vi-admin#19]
I just want to do my edit and the go back to the list. Currently I have to click twice: _save_ and then _tab close_.

**Comment by sveneberth** [comment]
the viur-meeting wants this button too

**Comment by XeoN-GHMB** [comment]
will be available in the next release: https://github.com/viur-framework/vi-vue-components/commit/41e5ec8f6a9222236160c4f412ad05cdb6c5299d
