### ISSUE TITLE
How can I upload multiple files at once?

### ISSUE THREAD

**Issue by sveneberth** [viur-framework/vi-admin#6]
Neither dragging and dropping multiple files works nor is it possible to select multiple files in the system file dialog (via "+ Datei hinzufügen").

**Comment by XeoN-GHMB** [comment]
this will be possible with the Filebrowser rework

**Comment by sveneberth** [comment]
Solved with new new file browser, thanks :rocket:

**Comment by sveneberth** [comment]
The field selection works again, but the first time the fields are not selected, the second time they are
