### ISSUE TITLE
If bone `name` is multi-lang the title is `undefined`

### ISSUE THREAD

**Issue by sveneberth** [viur-framework/vi-admin#9]
![image](https://github.com/viur-framework/vi-admin/assets/10272292/1f4e3805-8a2b-4bc0-a503-6501fe153a48)

**Comment by XeoN-GHMB** [comment]
fixed in the next version: https://github.com/viur-framework/vi-vue-components/commit/74071df7b8796b93983f94d1eb14b257f7f14846
